/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package gov.census.esoa.mft.rpc;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface MFTFileTransfer {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"MFTFileTransfer\",\"namespace\":\"gov.census.esoa.mft.rpc\",\"types\":[{\"type\":\"record\",\"name\":\"MFTPushRequest\",\"fields\":[{\"name\":\"clientId\",\"type\":\"string\"},{\"name\":\"fileName\",\"type\":\"string\"},{\"name\":\"offset\",\"type\":\"long\"},{\"name\":\"totalSize\",\"type\":\"long\"},{\"name\":\"body\",\"type\":\"bytes\"},{\"name\":\"remainingSize\",\"type\":\"long\"}]},{\"type\":\"record\",\"name\":\"MFTPushResponse\",\"fields\":[{\"name\":\"clientId\",\"type\":\"string\"},{\"name\":\"fileName\",\"type\":\"string\"},{\"name\":\"statusCode\",\"type\":\"int\"},{\"name\":\"consumedLength\",\"type\":\"long\"}]},{\"type\":\"record\",\"name\":\"MFTGetRequest\",\"fields\":[{\"name\":\"clientId\",\"type\":\"string\"},{\"name\":\"fileName\",\"type\":\"string\"},{\"name\":\"offset\",\"type\":\"long\"},{\"name\":\"length\",\"type\":\"long\"}]},{\"type\":\"record\",\"name\":\"MFTGetResponse\",\"fields\":[{\"name\":\"clientId\",\"type\":\"string\"},{\"name\":\"fileName\",\"type\":\"string\"},{\"name\":\"offset\",\"type\":\"long\"},{\"name\":\"body\",\"type\":\"bytes\"},{\"name\":\"remainingSize\",\"type\":\"long\"},{\"name\":\"totalSize\",\"type\":\"long\"}]}],\"messages\":{\"receive\":{\"request\":[{\"name\":\"mftPushRequest\",\"type\":\"MFTPushRequest\"}],\"response\":\"MFTPushResponse\"},\"get\":{\"request\":[{\"name\":\"mftGetRequest\",\"type\":\"MFTGetRequest\"}],\"response\":\"MFTGetResponse\"}}}");
  /**
   */
  gov.census.esoa.mft.rpc.MFTPushResponse receive(gov.census.esoa.mft.rpc.MFTPushRequest mftPushRequest) throws org.apache.avro.AvroRemoteException;
  /**
   */
  gov.census.esoa.mft.rpc.MFTGetResponse get(gov.census.esoa.mft.rpc.MFTGetRequest mftGetRequest) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends MFTFileTransfer {
    public static final org.apache.avro.Protocol PROTOCOL = gov.census.esoa.mft.rpc.MFTFileTransfer.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void receive(gov.census.esoa.mft.rpc.MFTPushRequest mftPushRequest, org.apache.avro.ipc.Callback<gov.census.esoa.mft.rpc.MFTPushResponse> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void get(gov.census.esoa.mft.rpc.MFTGetRequest mftGetRequest, org.apache.avro.ipc.Callback<gov.census.esoa.mft.rpc.MFTGetResponse> callback) throws java.io.IOException;
  }
}